FROM python:3.7-alpine

# Add img
RUN apk add --no-cache img --repository=http://dl-cdn.alpinelinux.org/alpine/edge/testing

# Setup other deps
RUN apk add --no-cache git skopeo docker

# Install taskboot from copied source code
COPY . /src/taskboot
pip cd /src/taskboot && install --no-cache-dir .

CMD ["taskboot", "--help"]
